In [1]:
import pandas as pd
import os
import numpy as np

In [2]:
#set the path of the processed data
processed_data_path = os.path.join(os.path.pardir,'data','processed')
train_file_path = os.path.join(processed_data_path,'train.csv')
test_file_path = os.path.join(processed_data_path,'test.csv')

In [3]:
# read the data with all default parameters
train_df = pd.read_csv(train_file_path,index_col='PassengerId')
test_df = pd.read_csv(test_file_path,index_col='PassengerId')

In [4]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 33 columns):
Survived              891 non-null int64
Age                   891 non-null float64
Fare                  891 non-null float64
FamilySize            891 non-null int64
IsMother              891 non-null int64
IsMale                891 non-null int64
Deck_A                891 non-null int64
Deck_B                891 non-null int64
Deck_C                891 non-null int64
Deck_D                891 non-null int64
Deck_E                891 non-null int64
Deck_F                891 non-null int64
Deck_G                891 non-null int64
Deck_Z                891 non-null int64
Pclass_1              891 non-null int64
Pclass_2              891 non-null int64
Pclass_3              891 non-null int64
Title_Lady            891 non-null int64
Title_Master          891 non-null int64
Title_Miss            891 non-null int64
Title_Mr              891 non-null int64
Title_Mrs             891 non-

In [5]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 418 entries, 892 to 1309
Data columns (total 32 columns):
Age                   418 non-null float64
Fare                  418 non-null float64
FamilySize            418 non-null int64
IsMother              418 non-null int64
IsMale                418 non-null int64
Deck_A                418 non-null int64
Deck_B                418 non-null int64
Deck_C                418 non-null int64
Deck_D                418 non-null int64
Deck_E                418 non-null int64
Deck_F                418 non-null int64
Deck_G                418 non-null int64
Deck_Z                418 non-null int64
Pclass_1              418 non-null int64
Pclass_2              418 non-null int64
Pclass_3              418 non-null int64
Title_Lady            418 non-null int64
Title_Master          418 non-null int64
Title_Miss            418 non-null int64
Title_Mr              418 non-null int64
Title_Mrs             418 non-null int64
Title_Officer         418 n

In [7]:
#Data preparation
x = train_df.loc[:,'Age':].as_matrix().astype('float')
y = train_df['Survived'].ravel()

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


In [11]:
print(x.shape,y.shape)

(891, 32) (891,)


In [13]:
# train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state = 0)
print(x_train.shape, y_train.shape)
print(x_test.shape,y_test.shape)

(712, 32) (712,)
(179, 32) (179,)


In [14]:
#average survival in train and test
print('Mean survival in train: {0:.3f}'.format(np.mean(y_train)))
print('Mean survival in test: {0:.3f}'.format(np.mean(y_test)))

Mean survival in train: 0.383427
Mean survival in test: 0.385475


In [15]:
#check Scikit learn version
import sklearn

In [16]:
sklearn.__version__

'0.19.1'

In [17]:
#baseline model
from sklearn.dummy import DummyClassifier

In [18]:
#create model
model_dummy = DummyClassifier(strategy = 'most_frequent',random_state = 0)

In [19]:
#train model
model_dummy.fit(x_train,y_train)

DummyClassifier(constant=None, random_state=0, strategy='most_frequent')

In [24]:
#Accuracy ot base model
print('Scoreline for base model: {0:.2f}'.format(model_dummy.score(x_test,y_test)))

Scoreline for base model: 0.61


In [25]:
#performane metrics
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score

In [27]:
#accuracy score
print('Accuracy of baseline model: {0:.2f}'.format(accuracy_score(y_test,model_dummy.predict(x_test))))

Accuracy of baseline model: 0.61


In [30]:
#confusion matrix
print('Confusion matrix of baseline model: \n{0}'.format(confusion_matrix(y_test,model_dummy.predict(x_test))))

Confusion matrix of baseline model: 
[[110   0]
 [ 69   0]]


In [35]:
#precision and recall score
print('Precision of baseline model: {0:.2f}'.format(precision_score(y_test,model_dummy.predict(x_test))))
print('Recall of baseline model: {0:.2f}'.format(recall_score(y_test,model_dummy.predict(x_test))))

Precision of baseline model: 0.00
Recall of baseline model: 0.00


D:\Anaconda\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


In [36]:
#first kaggle submission
#converting to the matrix
test_x = test_df.as_matrix().astype('float')

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  This is separate from the ipykernel package so we can avoid doing imports until


In [37]:
#get predictions
predictions = model_dummy.predict(test_x)

In [38]:
df_submission = pd.DataFrame({'PassengerId':test_df.index, 'Survived':predictions})

In [39]:
df_submission.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0

In [40]:
submission_data_path = os.path.join(os.path.pardir,'data','external')
submission_file_path = os.path.join(submission_data_path,'01_dummy.csv')

In [42]:
df_submission.to_csv(submission_file_path,index = False)

In [55]:
def get_submission_file(model,filename):
    #converting to the matrix
    test_X = test_df.as_matrix().astype('float')
    #make predictions
    predictions = model.predict(test_X)
    #submission dataframe
    df_submission = pd.DataFrame({'PassengerId':test_df.index, 'Survived':predictions})
    submission_data_path = os.path.join(os.path.pardir,'data','external')
    submission_file_path = os.path.join(submission_data_path,filename)
    #write to the file
    df_submission.to_csv(submission_file_path,index = False)

In [56]:
#get submission file
get_submission_file(model_dummy,'01_dummy.csv')

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  This is separate from the ipykernel package so we can avoid doing imports until


In [46]:
#logistic regression model
from sklearn.linear_model import LogisticRegression

In [47]:
#create model
model_lr_1 = LogisticRegression(random_state = 0)

In [48]:
#train model
model_lr_1.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [50]:
#evaluate model
print ("Score of logitic regression model version 1 is:{0:.2f}".format(model_lr_1.score(x_test,y_test)))

Score of logitic regression model version 1 is:0.83


In [51]:
#performance metrics
print('Accuracy of baseline model: {0:.2f}'.format(accuracy_score(y_test,model_lr_1.predict(x_test))))
print('Confusion matrix of baseline model: \n{0}'.format(confusion_matrix(y_test,model_lr_1.predict(x_test))))
print('Precision of baseline model: {0:.2f}'.format(precision_score(y_test,model_lr_1.predict(x_test))))
print('Recall of baseline model: {0:.2f}'.format(recall_score(y_test,model_lr_1.predict(x_test))))

Accuracy of baseline model: 0.83
Confusion matrix of baseline model: 
[[95 15]
 [15 54]]
Precision of baseline model: 0.78
Recall of baseline model: 0.78


In [52]:
#model coeficients
model_lr_1.coef_

array([[-0.02827104,  0.0045591 , -0.50374467,  0.67717726, -0.80602381,
         0.12651353, -0.17332936, -0.39103983,  0.52416017,  1.09828191,
         0.40381114, -0.18652557, -0.30075437,  0.96237481,  0.48458054,
        -0.34583774,  0.28247567,  1.22342267,  0.5756021 , -1.44467042,
         1.04906365, -0.11269524, -0.47208082,  0.16170614,  0.24113172,
         0.28229637,  0.41598337,  0.49150919,  0.46115935,  0.14844908,
         0.36744378,  0.73367383]])

In [57]:
#get second submission file
get_submission_file(model_lr_1,'02_dummy.csv')

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  This is separate from the ipykernel package so we can avoid doing imports until


In [58]:
# hyperparameter optimization using k fold crossvalidation
#base model
model_lr = LogisticRegression(random_state = 0)

In [59]:
from sklearn.model_selection import GridSearchCV

In [64]:
parameters = {'C':[1.0, 10.0, 50.0, 100.0, 1000.0],'penalty':['l1','l2']}
clf = GridSearchCV(model_lr, param_grid=parameters, cv =3)

In [65]:
clf.fit(x_train,y_train)

GridSearchCV(cv=3, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [1.0, 10.0, 50.0, 100.0, 1000.0], 'penalty': ['l1', 'l2']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [66]:
clf.best_params_

{'C': 1.0, 'penalty': 'l1'}

In [68]:
print('best score: {0:.2f}'.format(clf.best_score_))

best score: 0.83


In [71]:
#make third submission
get_submission_file(clf,'03_lr.csv')

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  This is separate from the ipykernel package so we can avoid doing imports until


In [72]:
#feature normalization and standardization
from sklearn.preprocessing import MinMaxScaler, StandardScaler
#MinMaxScaler is for normalization and StandardScaler is for standardization

In [74]:
#feature normalization
scaler = MinMaxScaler()
x_train_scaled = scaler.fit_transform(x_train)

In [76]:
x_train_scaled[:,0].min(),x_train_scaled[:,0].max()

(0.0, 1.0)

In [77]:
#normalize test data
x_test_scaled = scaler.transform(x_test)

In [78]:
#feature standardization
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [98]:
#create model after standardization
model_lr = LogisticRegression(random_state =0)
parameters = {'C':[1.0, 10.0, 50.0, 100.0, 1000.0],'penalty':['l1','l2']}
clf = GridSearchCV(model_lr, param_grid=parameters, cv =3)
clf.fit(x_train_scaled,y_train)

GridSearchCV(cv=3, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [1.0, 10.0, 50.0, 100.0, 1000.0], 'penalty': ['l1', 'l2']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [99]:
clf.best_score_

0.8132022471910112

In [100]:
#evaluate model
print ("Score of logitic regression model version 3 is:{0:.2f}".format(clf.score(x_test_scaled,y_test)))

Score of logitic regression model version 3 is:0.84


In [82]:
#make fourth submission
get_submission_file(clf,'04_lr.csv')

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  This is separate from the ipykernel package so we can avoid doing imports until


In [83]:
#model persistence using pickle
import pickle

In [89]:
#create the file paths
model_file_path = os.path.join(os.path.pardir,'models','lr_model_pkl')
scaler_file_path = os.path.join(os.path.pardir,'models','lr_scaler_pkl')

In [90]:
#open the files to write
model_file_pickle = open(model_file_path,'wb')
scaler_file_pickle = open(scaler_file_path,'wb')

In [91]:
#persist the model and scaler
pickle.dump(clf,model_file_pickle)
pickle.dump(scaler,scaler_file_pickle)

In [92]:
#close the file
model_file_pickle.close()
scaler_file_pickle.close()

In [94]:
#load the persisted file
#open files in read mode
model_file_pickle = open(model_file_path,'rb')
scaler_file_pickle = open(scaler_file_path,'rb')
#load files
clf_loaded = pickle.load(model_file_pickle)
scaler_loaded = pickle.load(scaler_file_pickle)
#close files
model_file_pickle.close()
scaler_file_pickle.close()

In [95]:
clf_loaded

GridSearchCV(cv=3, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [1.0, 10.0, 50.0, 100.0, 1000.0], 'penalty': ['l1', 'l2']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [96]:
scaler_loaded

StandardScaler(copy=True, with_mean=True, with_std=True)

In [97]:
x_test_scaled = scaler_loaded.transform(x_test)
print ("Score of logitic regression model version 3 is:{0:.2f}".format(clf_loaded.score(x_test_scaled,y_test)))

Score of logitic regression model version 3 is:0.84
